# version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: car_database
      POSTGRES_USER: onebyte
      POSTGRES_PASSWORD: ogbonna12345
    ports:
      - "5432:5432"

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
        - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.dev
    dns:
      - 8.8.8.8
      - 8.8.4.4

  # frontend:
  #     build: ../car-manager
  #     volumes:
  #       - ../car-manager:/app
  #     ports:
  #       - "3001:3000"
  #     depends_on:
  #       - backend